#include QMK_KEYBOARD_H
#include "caps_word.h"


enum combos {
    CAPSWORD_COMBO,
    COMBO_LENGTH
};

const uint16_t PROGMEM capsword_combo[] = {KC_D, KC_H, COMBO_END};
combo_t key_combos[COMBO_LENGTH] = {
    [CAPSWORD_COMBO] = COMBO_ACTION(capsword_combo),
};

void process_combo_event(uint16_t combo_index, bool pressed) {
    switch(combo_index) {
        case CAPSWORD_COMBO:
            if (pressed) {
                caps_word_toggle();
            }
            break;
    }
}

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, LGUI_T(KC_A), LALT_T(KC_R), LSFT_T(KC_S), LCTL_T(KC_T), KC_D, KC_H, RCTL_T(KC_N), RSFT_T(KC_E), RALT_T(KC_I), RGUI_T(KC_O), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, LT(3,KC_TAB), LT(1,KC_SPC), LT(4,KC_ENT), LT(2,KC_BSPC)),
    [1] = LAYOUT_split_3x5_2(KC_TILD, KC_HASH, KC_AT, KC_EXLM, KC_PLUS, KC_UNDS, KC_LCBR, KC_RCBR, KC_NO, KC_COLN, KC_GRV, KC_MINS, KC_PERC, KC_DLR, KC_EQL, KC_PGUP, KC_LPRN, KC_RPRN, KC_SCLN, KC_NO, KC_CIRC, KC_PIPE, KC_ASTR, KC_AMPR, KC_BSLS, KC_PGUP, KC_LBRC, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [2] = LAYOUT_split_3x5_2(KC_NO, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_HOME, KC_NO, KC_END, KC_NO, KC_0, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_NO, KC_NO, KC_NO),
    [3] = LAYOUT_split_3x5_2(KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, KC_NO, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [4] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};


//
// #ifdef OTHER_KEYMAP_C
// #    include OTHER_KEYMAP_C
// #endif // OTHER_KEYMAP_C
//
